Entity/Site.php
<?php

/*
 * This file is part of the Allegro package.
 *
 * (c) Arturo Rodríguez <arturo@fugadigital.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Allegro\SitesBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Allegro\SitesBundle\Repository\SiteRepository")
 * @ORM\Table(name="allegro_site",uniqueConstraints={@ORM\UniqueConstraint(name="uq_slug", columns={"slug"})})
 * @ORM\HasLifecycleCallbacks()
 */
class Site
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="SiteTranslation", mappedBy="site", cascade={"persist", "remove"})
     */
    protected $translations;

    /**
     * @ORM\OneToOne(targetEntity="SiteTranslation", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="main_translation_id", referencedColumnName="id", nullable=true, onDelete="CASCADE")
     */
    protected $mainTranslation;

    /**
     * @ORM\OneToMany(targetEntity="Page", mappedBy="site", cascade={"persist", "remove"})
     * @ORM\OrderBy({"pageOrder" = "ASC"})
     */
    protected $pages;

    /**
     * @ORM\OneToOne(targetEntity="Page")
     * @ORM\JoinColumn(name="landing_page_id", referencedColumnName="id", nullable=true, onDelete="CASCADE")
     */
    protected $landingPage;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $permanentLandingRedirect;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    protected $title;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    protected $slug;

    /**
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="author_id", referencedColumnName="id", nullable=false)
     */
    protected $createdBy;

   /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    protected $created;

    /**
     * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="update_author_id", referencedColumnName="id", nullable=true)
     */
    protected $modifiedBy;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $lastModified;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $enabled = true;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $contactEmail;


    // Virtual fields

    /* When creating a new obj from admin, this will
     obtain the main lang string like 'en' or 'es' */
    protected $mainLanguage;
    public function getMainLanguage()
    {
        return $this->mainLanguage;
    }

    public function setMainLanguage($mainLanguage)
    {
        $this->mainLanguage = $mainLanguage;
    }

    /* When creating a new obj from admin, this will
     obtain the site description for the main lang */
    protected $description;
    public function getDescription()
    {
        return $this->description;
    }
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /* When creating a new obj from admin, this will
     obtain a strings array e.g. array('es', 'en', 'fi') */
    protected $translationLanguages = array();
    public function getTranslationLanguages()
    {
        return $this->translationLanguages;
    }
    public function setTranslationLanguages($translationLanguages)
    {
        $this->translationLanguages = $translationLanguages;
    }

    /* When updating pages tree this will containt the new structure */
    protected $menuOrder;
    public function getMenuOrder() {
        return $this->menuOrder;
    }
    public function setMenuOrder($menuOrder)
    {
        $this->menuOrder = $menuOrder;
    }

    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

    public function __toString()
    {
        return (empty($this->id))
            ? 'New site'
            : $this->getTitle();
    }

    public function __construct()
    {
        $this->translations = new ArrayCollection();
        $this->pages = new ArrayCollection();
    }

    /**
     * Gets the lenguage set in the main translation for this site
     * 
     * @return string The language
     */
    public function getMainLang() {
        return null !== $this->getMainTranslation()
            ? $this->getMainTranslation()->getLang()
            : 'n/a';
    }

    /**
     * Obtains a string array with the available translations for the current
     * site. The first element is the main translation.
     * 
     * @return array array('xx', 'yy', 'zz')
     */
    public function getAllTranslations() {
        $main = $this->getMainTranslation()->getLang();
        $locales = array($main);
        foreach ($this->getTranslations() as $translation) {
            $lang = $translation->getLang();
            if ($lang !== $main) {
                $locales[] = $lang;
            }
        }

        return $locales;
    }

    /**
     * Obtains the site pages without parent.
     * 
     * @return \Doctrine\Common\Collections\Collection pages sorted by configured order
     */
    public function getFirstPages() {
        $pages = array();
        foreach ($this->pages as $page) {
            if (null === $page->getParent()) {
                $pages[] = $page;
            }
        }

        return new \Doctrine\Common\Collections\ArrayCollection($pages);
    }

    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
    /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set permanentLandingRedirect
     *
     * @param string $permanentLandingRedirect
     * @return Site
     */
    public function setPermanentLandingRedirect($permanentLandingRedirect)
    {
        $this->permanentLandingRedirect = $permanentLandingRedirect;

        return $this;
    }

    /**
     * Get permanentLandingRedirect
     *
     * @return string
     */
    public function getPermanentLandingRedirect()
    {
        return $this->permanentLandingRedirect;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Site
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Site
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Site
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set lastModified
     *
     * @param \DateTime $lastModified
     * @return Site
     */
    public function setLastModified($lastModified)
    {
        $this->lastModified = $lastModified;

        return $this;
    }

    /**
     * Get lastModified
     *
     * @return \DateTime
     */
    public function getLastModified()
    {
        return $this->lastModified;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return Site
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * Get enabled
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Add pages
     *
     * @param \Allegro\SitesBundle\Entity\Page $pages
     * @return Site
     */
    public function addPage(\Allegro\SitesBundle\Entity\Page $pages)
    {
        $this->pages[] = $pages;

        return $this;
    }

    /**
     * Remove pages
     *
     * @param \Allegro\SitesBundle\Entity\Page $pages
     */
    public function removePage(\Allegro\SitesBundle\Entity\Page $pages)
    {
        $this->pages->removeElement($pages);
    }

    /**
     * Get pages
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPages()
    {
        return $this->pages;
    }

    /**
     * Set createdBy
     *
     * @param \Application\Sonata\UserBundle\Entity\User $createdBy
     * @return Site
     */
    public function setCreatedBy(\Application\Sonata\UserBundle\Entity\User $createdBy)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \Application\Sonata\UserBundle\Entity\User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set modifiedBy
     *
     * @param \Application\Sonata\UserBundle\Entity\User $modifiedBy
     * @return Site
     */
    public function setModifiedBy(\Application\Sonata\UserBundle\Entity\User $modifiedBy)
    {
        $this->modifiedBy = $modifiedBy;

        return $this;
    }

    /**
     * Get modifiedBy
     *
     * @return \Application\Sonata\UserBundle\Entity\User
     */
    public function getModifiedBy()
    {
        return $this->modifiedBy;
    }

    /**
     * Add translations
     *
     * @param \Allegro\SitesBundle\Entity\SiteTranslation $translations
     * @return Site
     */
    public function addTranslation(\Allegro\SitesBundle\Entity\SiteTranslation $translations)
    {

Controller/CRUDController.php
<?php

/*
 * This file is part of the Allegro package.
 *
 * (c) Arturo Rodríguez <arturo@fugadigital.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Allegro\SitesBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController as Controller;
use Sonata\AdminBundle\Exception\ModelManagerException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class CRUDController extends Controller
{
    /**
     * Return the Response object associated to the create action. This method
     * is defined to add the parent site id in the route. This makes it available
     * in the admin form through the request object.
     * 
     * @param string $parentId
     * @return Response
     * @throws AccessDeniedException
     */
    public function createPageAction($parentId)
    {
        return $this->createAction();
    }

    public function pagesTreeAction()
    {
        // the key used to lookup the template
        $templateKey = 'pages_tree';

        $id = $this->get('request')->get($this->admin->getIdParameter());
        $object = $this->admin->getObject($id);

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }

        if (false === $this->admin->isGranted('EDIT', $object)) {
            throw new AccessDeniedException();
        }

        $this->admin->setSubject($object);

        /**
         * This will hold the built form from custom *Admin. getForm() calls
         * configureFormFields() from the custom SiteAdmin class
         * 
         * @var \Symfony\Component\Form\Form $form
         */
        $form = $this->admin->getForm();
        $form->setData($object);

        if ($this->getRestMethod() == 'POST') {
            $form->submit($this->get('request'));

            $isFormValid = $form->isValid();

            // persist if the form was valid and if in preview mode the preview was approved
            if ($isFormValid && (!$this->isInPreviewMode() || $this->isPreviewApproved())) {
                
                // modify a field to trigger update (and crud listener)
                $object->setLastModified(new \DateTime());

                $this->admin->update($object);

                if ($this->isXmlHttpRequest()) {
                    return $this->renderJson(array(
                        'result'    => 'ok',
                        'objectId'  => $this->admin->getNormalizedIdentifier($object)
                    ));
                }

                $this->addFlash('sonata_flash_success', $this->admin->trans(
                    'flash_edit_success',
                    array('%name%' => $this->admin->toString($object)),
                    'SonataAdminBundle'
                ));

                // redirect to tree
                return $this->redirect(
                    $this->generateUrl(
                        'admin_allegro_sites_site_pages_tree',
                        array('id' => $object->getId())
                ));
            }

            // show an error message if the form failed validation
            if (!$isFormValid) {
                if (!$this->isXmlHttpRequest()) {
                    $this->addFlash('sonata_flash_error', $this->admin->trans(
                        'flash_edit_error',
                        array('%name%' => $this->admin->toString($object)), 'SonataAdminBundle'
                    ));
                }
            }
        }

        $view = $form->createView();

        // set the theme for the current Admin Form
        $this->get('twig')->getExtension('form')->renderer->setTheme($view, $this->admin->getFormTheme());

        return $this->render($this->admin->getTemplate($templateKey), array(
            'action' => 'pages_tree',
            'form'   => $view,
            'object' => $object,
        ));
    }

    /**
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException|\Symfony\Component\Security\Core\Exception\AccessDeniedException
     *
     * @param mixed $id
     *
     * @return Response|RedirectResponse
     */
    public function deleteAction($id)
    {
        $id     = $this->get('request')->get($this->admin->getIdParameter());
        $object = $this->admin->getObject($id);

        if (!$object) {
            throw new NotFoundHttpException(sprintf('unable to find the object with id : %s', $id));
        }

        if (false === $this->admin->isGranted('DELETE', $object)) {
            throw new AccessDeniedException();
        }

        if ($this->getRestMethod() == 'DELETE') {
            // check the csrf token
            $this->validateCsrfToken('sonata.delete');

            try {
                $this->admin->delete($object);

                if ($this->isXmlHttpRequest()) {
                    return $this->renderJson(array('result' => 'ok'));
                }

                $this->addFlash(
                    'sonata_flash_success',
                    $this->admin->trans(
                        'flash_delete_success',
                        array('%name%' => $this->admin->toString($object)),
                        'SonataAdminBundle'
                    )
                );

            } catch (ModelManagerException $e) {

                //get details of the PDO or DBAL exeption that was actually thrown
                $actualException = $e->getPrevious();
                if ($this->isXmlHttpRequest()) {
                    return $this->renderJson(
                        array(
                            'result' => 'error', 
                            'info' => $actualException->getMessage()
                        )
                    );
                }

                $this->addFlash(
                    'sonata_flash_error',
                    $this->admin->trans(
                        'flash_delete_error',
                        array('%name%' => $this->admin->toString($object)),
                        'SonataAdminBundle'
                    )
                );
                $this->addFlash(
                    'sonata_flash_error',
                    $actualException->getMessage()
                );
            }

            $refRequest = $this->get('request')->headers->get('referer');

            if (false !== strpos($refRequest, '?')) {
                $query = substr($refRequest, strpos($refRequest, '?')+1);
                parse_str($query, $params);

                if (key_exists('ref', $params)) {
                    if ('tree' === $params['ref']) {
                        $id = $this->get('request')->get($this->admin->getParent()->getIdParameter());
                        $redirectUrl = $this->admin->getParent()->generateUrl('pages_tree', array('id' => $id));
                    }
                }
            }

            if (!isset($redirectUrl)) {
                $redirectUrl = $this->admin->generateUrl('list');
            }

            return new RedirectResponse($redirectUrl);
        }

        return $this->render($this->admin->getTemplate('delete'), array(
            'object'     => $object,
            'action'     => 'delete',
            'csrf_token' => $this->getCsrfToken('sonata.delete')
        ));
    }
    /* */
}

Resources/views/CRUD/list__action_pages_tree.html.twig
{#

This file is part of the Allegro Package.

(c) Arturo Rodríguez <arturo@fugadigital.com>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

<a class="btn btn-sm btn-default edit_link" title="Tree" href="{{ admin.generateObjectUrl('pages_tree', object) }}">
    <i class="glyphicon glyphicon-indent-left"></i>
    Tree
</a>

Resources/views/CRUD/pages_tree.html.twig
{#

This file is part of the Allegro Package.

(c) Arturo Rodríguez <arturo@fugadigital.com>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends 'AllegroSitesBundle:Admin:standard_layout.html.twig' %}

{# Starts Sonata Admin base_edit.html.twig #}

{% block title %}{% endblock%}

{% block navbar_title %}
    {{ block('title') }}
{% endblock %}

{% block actions %}
    <li>{% include 'SonataAdminBundle:Button:show_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:history_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:acl_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:list_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:create_button.html.twig' %}</li>
{% endblock %}

{% block tab_menu %}{{ knp_menu_render(admin.sidemenu(action), {'currentClass' : 'active'}, 'list') }}{% endblock %}

{# Ends Sonata Admin base_edit.html.twig #}

{# Starts Sonata Admin base_edit_form.html.twig #}

{% block form %}
    {{ sonata_block_render_event('sonata.admin.edit.form.top', { 'admin': admin, 'object': object }) }}

    {% set url = 'pages_tree' %}

    {% if not admin.hasRoute(url)%}
        <div>
            {{ "form_not_available"|trans({}, "SonataAdminBundle") }}
        </div>
    {% elseif 0 == object.firstPages|length %}
        <div class="callout callout-info">
            {{ 'no_result'|trans({}, 'SonataAdminBundle') }}
        </div>
   {% else %}
        <form class="form-horizontal"
              action="{{ admin.generateUrl(url, {'id': admin.id(object), 'uniqid': admin.uniqid, 'subclass': app.request.get('subclass')}) }}" {{ form_enctype(form) }}
              method="POST"
              {% if not admin_pool.getOption('html5_validate') %}novalidate="novalidate"{% endif %}
              >
            {% if form.vars.errors|length > 0 %}
                <div class="sonata-ba-form-error">
                    {{ form_errors(form) }}
                </div>
            {% endif %}

            {% block sonata_pre_fieldsets %}
                <div class="row">
            {% endblock %}

            {% block sonata_tab_content %}
                {% for name, form_group in admin.formgroups %}
                    <div class="{{ form_group.class|default('col-md-12') }}">
                        <div class="box box-success">
                            <div class="box-header">
                                <h4 class="box-title">
                                    {{ admin.trans(name, {}, form_group.translation_domain) }}
                                </h4>
                            </div>
                            <div class="box-body">
                                <div class="sonata-ba-collapsed-fields">
                                    {% if form_group.description != false %}
                                        <p>{{ form_group.description|raw }}</p>
                                    {% endif %}

                                    {% for field_name in form_group.fields %}
                                        {% if admin.formfielddescriptions[field_name] is defined %}
                                            {{ form_row(form[field_name])}}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endblock %}

            {% block sonata_post_fieldsets %}
                </div>
            {% endblock %}

            {{ form_rest(form) }}

            {% block formactions %}
                <div class="well well-small form-actions">
                    {% if app.request.isxmlhttprequest %}
                        <button type="submit" class="btn btn-success" name="btn_update"><i class="fa fa-save"></i> {{ 'btn_update'|trans({}, 'SonataAdminBundle') }}</button>
                    {% else %}
                        <button type="submit" class="btn btn-success" name="btn_update_and_edit"><i class="fa fa-save"></i> {{ 'btn_update_and_edit_again'|trans({}, 'SonataAdminBundle') }}</button>

                        {% if admin.hasroute('list') %}
                            <button type="submit" class="btn btn-success" name="btn_update_and_list"><i class="fa fa-save"></i> <i class="fa fa-list"></i> {{ 'btn_update_and_return_to_list'|trans({}, 'SonataAdminBundle') }}</button>
                        {% endif %}

                        {% if admin.isAclEnabled() and admin.hasroute('acl') and admin.isGranted('MASTER', object) %}
                            <a class="btn btn-info" href="{{ admin.generateObjectUrl('acl', object) }}"><i class="fa fa-users"></i> {{ 'link_edit_acl'|trans({}, 'SonataAdminBundle') }}</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% endblock formactions %}
        </form>
    {% endif%}

    {{ sonata_block_render_event('sonata.admin.edit.form.bottom', { 'admin': admin, 'object': object }) }}

{% endblock %}